-- Ghana Regulatory Events Database Schema

-- Countries table
CREATE TABLE countries (
    code VARCHAR(10) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    who_maturity_level INT
);

-- Companies table
CREATE TABLE companies (
    id SERIAL PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    country_code VARCHAR(10) REFERENCES countries(code),
    founding_date DATE,
    promoter_founder_name VARCHAR(200),
    company_brief TEXT,
    type VARCHAR(50) CHECK (type IN ('Manufacturer','Reselling Firm')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Regulatory events table
CREATE TABLE regulatory_events (
    id SERIAL PRIMARY KEY,
    event_type VARCHAR(50) CHECK (event_type IN ('Alert','Public Notice','Product Recall')),
    
    -- Alert fields
    alert_date DATE,
    alert_name VARCHAR(255),
    all_text TEXT,
    
    -- Public Notice fields
    notice_date DATE,
    notice_text TEXT,
    
    -- Product Recall fields
    recall_date DATE,
    product_name VARCHAR(255),
    product_type VARCHAR(100),
    manufacturer_id INT REFERENCES companies(id),
    recalling_firm_id INT REFERENCES companies(id),
    batches VARCHAR(255),
    manufacturing_date DATE,
    expiry_date DATE,
    
    -- Common fields
    source_url TEXT,
    pdf_path TEXT,
    reason_for_action TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for better performance
CREATE INDEX idx_regulatory_events_type ON regulatory_events(event_type);
CREATE INDEX idx_regulatory_events_date ON regulatory_events(alert_date, notice_date, recall_date);
CREATE INDEX idx_companies_name ON companies(name);
CREATE INDEX idx_companies_type ON companies(type);

-- Insert some default countries
INSERT INTO countries (code, name, who_maturity_level) VALUES 
('GH', 'Ghana', 3),
('US', 'United States', 4),
('UK', 'United Kingdom', 4),
('CN', 'China', 3),
('IN', 'India', 3),
('DE', 'Germany', 4),
('FR', 'France', 4),
('IT', 'Italy', 4),
('ES', 'Spain', 4),
('NL', 'Netherlands', 4),
('BE', 'Belgium', 4),
('CH', 'Switzerland', 4),
('AT', 'Austria', 4),
('SE', 'Sweden', 4),
('NO', 'Norway', 4),
('DK', 'Denmark', 4),
('FI', 'Finland', 4),
('IE', 'Ireland', 4),
('PT', 'Portugal', 4),
('GR', 'Greece', 4),
('PL', 'Poland', 4),
('CZ', 'Czech Republic', 4),
('HU', 'Hungary', 4),
('SK', 'Slovakia', 4),
('SI', 'Slovenia', 4),
('EE', 'Estonia', 4),
('LV', 'Latvia', 4),
('LT', 'Lithuania', 4),
('LU', 'Luxembourg', 4),
('MT', 'Malta', 4),
('CY', 'Cyprus', 4),
('BG', 'Bulgaria', 4),
('RO', 'Romania', 4),
('HR', 'Croatia', 4),
('RS', 'Serbia', 3),
('BA', 'Bosnia and Herzegovina', 2),
('MK', 'North Macedonia', 3),
('AL', 'Albania', 3),
('ME', 'Montenegro', 3),
('XK', 'Kosovo', 2),
('MD', 'Moldova', 2),
('UA', 'Ukraine', 3),
('BY', 'Belarus', 2),
('RU', 'Russia', 3),
('TR', 'Turkey', 3),
('IL', 'Israel', 4),
('SA', 'Saudi Arabia', 3),
('AE', 'United Arab Emirates', 3),
('QA', 'Qatar', 3),
('KW', 'Kuwait', 3),
('BH', 'Bahrain', 3),
('OM', 'Oman', 3),
('JO', 'Jordan', 3),
('LB', 'Lebanon', 2),
('EG', 'Egypt', 3),
('MA', 'Morocco', 3),
('TN', 'Tunisia', 3),
('DZ', 'Algeria', 2),
('LY', 'Libya', 1),
('SD', 'Sudan', 1),
('SS', 'South Sudan', 1),
('ET', 'Ethiopia', 2),
('KE', 'Kenya', 3),
('UG', 'Uganda', 2),
('TZ', 'Tanzania', 2),
('RW', 'Rwanda', 2),
('BI', 'Burundi', 1),
('DJ', 'Djibouti', 2),
('SO', 'Somalia', 1),
('ER', 'Eritrea', 1),
('MG', 'Madagascar', 2),
('MU', 'Mauritius', 3),
('SC', 'Seychelles', 3),
('KM', 'Comoros', 1),
('MW', 'Malawi', 2),
('ZM', 'Zambia', 2),
('ZW', 'Zimbabwe', 2),
('BW', 'Botswana', 3),
('NA', 'Namibia', 3),
('SZ', 'Eswatini', 2),
('LS', 'Lesotho', 2),
('ZA', 'South Africa', 4),
('AO', 'Angola', 2),
('CM', 'Cameroon', 2),
('CF', 'Central African Republic', 1),
('TD', 'Chad', 1),
('CG', 'Republic of the Congo', 2),
('CD', 'Democratic Republic of the Congo', 1),
('GQ', 'Equatorial Guinea', 2),
('GA', 'Gabon', 2),
('ST', 'São Tomé and Príncipe', 2),
('BF', 'Burkina Faso', 1),
('BJ', 'Benin', 2),
('CI', 'Côte d\'Ivoire', 2),
('GM', 'Gambia', 2),
('GN', 'Guinea', 1),
('GW', 'Guinea-Bissau', 1),
('LR', 'Liberia', 2),
('ML', 'Mali', 1),
('MR', 'Mauritania', 2),
('NE', 'Niger', 1),
('NG', 'Nigeria', 2),
('SN', 'Senegal', 2),
('SL', 'Sierra Leone', 2),
('TG', 'Togo', 2),
('CV', 'Cape Verde', 3),
('JP', 'Japan', 4),
('KR', 'South Korea', 4),
('KP', 'North Korea', 1),
('MN', 'Mongolia', 2),
('MM', 'Myanmar', 1),
('TH', 'Thailand', 3),
('LA', 'Laos', 2),
('KH', 'Cambodia', 2),
('VN', 'Vietnam', 3),
('MY', 'Malaysia', 3),
('SG', 'Singapore', 4),
('ID', 'Indonesia', 3),
('BN', 'Brunei', 3),
('PH', 'Philippines', 2),
('TL', 'East Timor', 2),
('PG', 'Papua New Guinea', 2),
('AU', 'Australia', 4),
('NZ', 'New Zealand', 4),
('FJ', 'Fiji', 2),
('SB', 'Solomon Islands', 2),
('VU', 'Vanuatu', 2),
('NC', 'New Caledonia', 4),
('PF', 'French Polynesia', 4),
('WS', 'Samoa', 2),
('TO', 'Tonga', 2),
('KI', 'Kiribati', 2),
('TV', 'Tuvalu', 2),
('NR', 'Nauru', 2),
('PW', 'Palau', 2),
('FM', 'Micronesia', 2),
('MH', 'Marshall Islands', 2),
('CA', 'Canada', 4),
('MX', 'Mexico', 3),
('GT', 'Guatemala', 2),
('BZ', 'Belize', 2),
('SV', 'El Salvador', 2),
('HN', 'Honduras', 2),
('NI', 'Nicaragua', 2),
('CR', 'Costa Rica', 3),
('PA', 'Panama', 3),
('CU', 'Cuba', 3),
('JM', 'Jamaica', 2),
('HT', 'Haiti', 1),
('DO', 'Dominican Republic', 2),
('PR', 'Puerto Rico', 4),
('TT', 'Trinidad and Tobago', 3),
('GD', 'Grenada', 2),
('VC', 'Saint Vincent and the Grenadines', 2),
('LC', 'Saint Lucia', 2),
('DM', 'Dominica', 2),
('AG', 'Antigua and Barbuda', 2),
('KN', 'Saint Kitts and Nevis', 2),
('BB', 'Barbados', 3),
('BS', 'Bahamas', 3),
('SR', 'Suriname', 2),
('GY', 'Guyana', 2),
('VE', 'Venezuela', 2),
('CO', 'Colombia', 3),
('BR', 'Brazil', 3),
('EC', 'Ecuador', 2),
('PE', 'Peru', 3),
('BO', 'Bolivia', 2),
('PY', 'Paraguay', 2),
('UY', 'Uruguay', 3),
('AR', 'Argentina', 3),
('CL', 'Chile', 3),
('FK', 'Falkland Islands', 4),
('GS', 'South Georgia and the South Sandwich Islands', 4),
('IS', 'Iceland', 4),
('GL', 'Greenland', 4),
('FO', 'Faroe Islands', 4),
('SJ', 'Svalbard and Jan Mayen', 4),
('AX', 'Åland Islands', 4),
('GG', 'Guernsey', 4),
('JE', 'Jersey', 4),
('IM', 'Isle of Man', 4),
('GI', 'Gibraltar', 4),
('VA', 'Vatican City', 4),
('SM', 'San Marino', 4),
('AD', 'Andorra', 4),
('MC', 'Monaco', 4),
('LI', 'Liechtenstein', 4),
('KZ', 'Kazakhstan', 3),
('KG', 'Kyrgyzstan', 2),
('TJ', 'Tajikistan', 2),
('TM', 'Turkmenistan', 2),
('UZ', 'Uzbekistan', 2),
('AF', 'Afghanistan', 1),
('PK', 'Pakistan', 2),
('BD', 'Bangladesh', 2),
('BT', 'Bhutan', 2),
('NP', 'Nepal', 2),
('LK', 'Sri Lanka', 3),
('MV', 'Maldives', 2),
('IR', 'Iran', 3),
('IQ', 'Iraq', 2),
('SY', 'Syria', 1),
('AM', 'Armenia', 3),
('AZ', 'Azerbaijan', 3),
('GE', 'Georgia', 3),
('CX', 'Christmas Island', 4),
('CC', 'Cocos (Keeling) Islands', 4),
('NF', 'Norfolk Island', 4),
('HM', 'Heard Island and McDonald Islands', 4),
('AQ', 'Antarctica', NULL);

ON CONFLICT (code) DO NOTHING;
