name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_ghana_regulatory
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install
    
    - name: Set up database
      run: |
        PGPASSWORD=postgres psql -h localhost -U postgres -d test_ghana_regulatory -f schema.sql
      env:
        PGPASSWORD: postgres
    
    - name: Run tests
      run: |
        python test_db_connection.py
      env:
        DB_HOST: localhost
        DB_NAME: test_ghana_regulatory
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_PORT: 5432
    
    - name: Test scraper with limit
      run: |
        python run_scraper.py
      env:
        DB_HOST: localhost
        DB_NAME: test_ghana_regulatory
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_PORT: 5432
        SCRAPE_LIMIT: 1
        HEADLESS_BROWSER: true